version: '3'

services:
  hl7-integration:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # REST API
      - "5000:5000"  # Web Interface
    volumes:
      - ./logs:/app/rest-receiver/logs
      - ./storage:/app/rest-receiver/storage
    environment:
      - NODE_ENV=development
      - HL7_API_ENDPOINT=http://localhost:3000/api/hl7
    restart: unless-stopped 